### ISSUE TITLE
Costum rendering column

### ISSUE THREAD

**Issue by iwasingh** [jbaysolutions/vue-bootstrap-table#13]
Hello, i have a problem.
I tried to render a button in a column like this.
`renderfunction: function (colname, entry) {
    return '<a href="#" class="btn btn-danger" v-on:click.once="destroy('+entry.deleted+')">'+
       '<i class="fa fa-trash"></i>'+
       '</a>';
}
`
entry.deleted is a integer got from the server after a request made by Axios
The problem is that button click not works, it doesn't call the destroy method. I think it is not "compiled" and that means it will not be handled by Vue.
How to render custom elements(like buttons)  with Vue template syntax?

I'm using Vue 2

**Comment by syshex** [comment]
for vue2 :  https://github.com/jbaysolutions/vue2-bootstrap-table

But just for the record , the renderFunction is a javascript function that gets called after vue is instantiated, etc etc etc. So by the point we get to call the render funcion, you can no longer use vue stuff like  v-on, etc etc etc.
