### ISSUE TITLE
Ability to perform XSS attack

### ISSUE THREAD

**Issue by vladyc9** [jbaysolutions/vue-bootstrap-table#14]
In case we use **renderfunction** method to customize column output the library uses v-html directive (as per source code) to display the result. Therefore, injecting malicious code, store it on the server and then renders causes script execution.

I can suggest to use {{ }} for rendering instead of v-html directive.

**Comment by gmsa** [comment]
{{ }} won't render html

**Comment by syshex** [comment]
@vladyc9  any other suggestions ? because the idea is really for you to be able to put in any html code desired.

**Comment by vladyc9** [comment]
@syshex I used sanitize-html library to round the problem
