### ISSUE TITLE
How to use this with nuxt framework

### ISSUE THREAD

**Issue by sudhir600** [jbaysolutions/vue-bootstrap-table#15]
I want to use this plugin in nuxt framework. I am using vue2.
What i  am trying is -
I created a plugin file - table.js and added this code there.

```
import Vue from 'vue';

export default ({ app, store, req }) => {
	components: {
        VueBootstrapTable: VueBootstrapTable
    }
}
```

and then  added in nuxt.config.js
```
plugins: [
           { src: '~/plugins/i18n.js'},
           { src: '~/plugins/table.js'},
.....

```

But i am getting this error - "**_VueBootstrapTable is not defined_**"

I think i am not intirating correctlyt. It will be great if you add the steps in your read me file.

**Comment by syshex** [comment]
Hi there , never used or heard of nuxt framework. 
Not sure what you are trying to do. Have you looked at the example provided in the source code?

**Comment by syshex** [comment]
Also, this project is only for vue1 . 
For vue2 : https://github.com/jbaysolutions/vue2-bootstrap-table

**Comment by sudhir600** [comment]
Nuxt is framework for VueJS.
there is slight difference to write code compare to vuejs native. 
See this - [https://nuxtjs.org/](https://nuxtjs.org/)
