### ISSUE TITLE
How to reload ajax?

### ISSUE THREAD

**Issue by tranchau1991** [jbaysolutions/vue-bootstrap-table#17]
ajax have parameter and how to call reload ajax?

**Comment by syshex** [comment]
Using Vue 1 or Vue 2 ?

**Comment by tranchau1991** [comment]
Use Vuejs 2

**Comment by syshex** [comment]
for Vue 2 use   https://github.com/jbaysolutions/vue2-bootstrap-table

**Comment by syshex** [comment]
For version 1.1.12 of the Vue2 : 
https://github.com/jbaysolutions/vue2-bootstrap-table/wiki/Public-Methods
